# Project information
site_name: Zabbix Book
#site_url: https://penmasters.github.io/zabbix-book/
site_url: https://thezabbixbook.com/
site_author: The Monitoring Penmasters
site_description: An open-source Zabbix book
copyright: Copyright &copy; 2025 Stichting The Monitoring Penmasters

# Repository
repo_name: penmasters
repo_url: https://github.com/penmasters/zabbix-book
edit_uri: edit/main/docs
docs_dir: docs

# Navigation
nav:
  - "Welcome": "index.md"
  - "Guidlines": "Guidelines.md"
  - "Getting started":
      - ch0-getting-started/initial-steps.md
      - ch0-getting-started/Requirements.md
  - "Chapter 1 : Zabbix components":
      - ch1-zabbix-components/chapter.md
      - ch1-zabbix-components/basic-installation.md
      - ch1-zabbix-components/ha-setup.md
  - "Chapter 2 : Installation":
      - ch2-zabbix-installation/chapter.md
      - ch2-zabbix-installation/frontend.md
      - ch2-zabbix-installation/host-groups.md
      - ch2-zabbix-installation/user-groups.md
      - ch2-zabbix-installation/external-authentication.md
  - "Chapter 3 : Proxies and Webcomponents": 
      - ch3-zabbix-proxies/chapter.md
      - ch3-zabbix-proxies/passive-proxies.md
      - ch3-zabbix-proxies/active-proxies.md
      - ch3-zabbix-proxies/web-services.md
  - "Chapter 4 : Collecting data ":
      - ch4-zabbix-collecting-data/chapter.md
      - ch4-zabbix-collecting-data/dataflow.md
      - ch4-zabbix-collecting-data/protocols.md
      - ch4-zabbix-collecting-data/hosts.md
  - "Chapter 5 : Triggers":
      - ch5-zabbix-triggers/chapter.md
      - ch5-zabbix-triggers/triggers.md
      - ch5-zabbix-triggers/advanced-triggers.md
  - "Chapter 6 : Templates":
      - ch6-zabbix-templates/chapter.md
  - "Chapter 7 : Alerting": 
      - ch7-zabbix-alerts/chapter.md
  - "Chapter 8 : LLD":
      - ch8-zabbix-lld/chapter.md
  - "Chapter 9 : Extending Zabbix": 
      - ch9-zabbix-extending/chapter.md
  - "Chapter 10 : Discovery": 
      - ch10-zabbix-discovery/chapter.md
  - "Chapter 11 : Visualisation":
      - ch11-zabbix-visualisation/chapter.md
  - "Chapter 12 : Zabbix API":
      - ch12-zabbix-api/chapter.md
  - "Chapter 13 : Real world examples":
      - ch13-zabbix-real-world-examples/chapter.md

theme:
  language: en
  name: material
  custom_dir: docs/overrides
  font:
    text: Roboto
    code: Nunito
  icon:
    logo: material/library
  features:
#    - navigation.tabs #add navigation to the top
    - navigation.expand
    - navigation.prune
    - navigation.path
#    - navigation.sections # removes the collapsable menu
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.view
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - fr
        - de
        - it
        - nl
        - pt  
        - es
        - th
        - zh 
        - en

  - privacy #GDPR compliance
  - spellcheck:
      backends:  # the backends you want to use
      - symspellpy  # as strings
      - codespell:  # or nested configs
          dictionaries: [clear, rare]

      # known_words can also be a list of words
      known_words: known_words.txt

      # ignore words in <code> tags
      ignore_code: yes

      # minimum length of words to consider
      min_length: 2

      # maximum number of capital letters in a word
      max_capital: 1

      # keep unicode characters
      allow_unicode: no

      # skip files entirely (supports Unix shell-style wildcards)
      skip_files:
      - fr/*
      - de/*
      - it/*
      - nl/*
      - pt/*
      - es/*
      - th/*
      - zh/*
    # - credits.md
    #- coverage.md
    #- reference/* 

      # whether to only check in strict mode
      strict_only: no

  - i18n:
      reconfigure_material: true
      fallback_to_default: true
      docs_structure: folder
      languages:
        - locale: fr
          name: Français
          build: true
        - locale: de
          name: German
          build: true
        - locale: it
          name: Italian
          build: true
        - locale: nl
          name: Nederlands
          build: true
        - locale: pt
          name: Portuguese
          build: true
        - locale: es
          name: Spanish
          build: true
        - locale: th
          name: ภาษาไทย
          build: true
        - locale: zh
          name: 中国人
          build: true
        - locale: en
          default: true
          name: English
          build: true

  - print-site:
      add_to_navigation: false
      print_page_title: "Print Book"
      # Table of contents
      add_table_of_contents: true
      toc_title: "Table of Contents"
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: false
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.progressbar
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
