# Project information
site_name: Zabbix Book
site_url: https://penmasters.github.io/zabbix-book/
site_author: The Monitoring Penmasters
site_description: An open-source Zabbix book
copyright: to do

# Repository
repo_name: penmasters
repo_url: https://github.com/penmasters/zabbix-book
edit_uri: edit/main/docs
docs_dir: docs

# Navigation
nav:
  - "Welcome": "index.md"
  - "Guidlines": "Guidlines.md"
  - "Getting started":
      - getting-started/initial-steps.md
      - getting-started/Requirements.md
  - "Installation and Configuration":
      - installation/installing-zabbixdb.md
      - installation/installing-zabbix.md
      - installation/installing-zabbix-ha.md
  - "Understanding the Essentials":
      - understanding-essentials/core-concepts.md
      - understanding-essentials/navigating-zabbix-interface.md
      - understanding-essentials/usermanagement.md
  - "Host and Network Configuration":
      - host-network-config/defining-zabbix-hosts.md
      - host-network-config/organazing-with-hostgroups.md
      - host-network-config/interfaces-templates.md
      - host-network-config/items-data-collection.md
  - "Problem Detection and Alerts":
      - problem-detection-alerts/zabbix-triggers.md
      - problem-detection-alerts/using-macros.md
      - problem-detection-alerts/how-information-travels.md
      - problem-detection-alerts/automating-actions.md
  - "Permission Management":
      - permission-management/user-groups.md
  - "Data Visualization":
      - data-visualization/visualising-problems.md
  - "Advanced Monitoring Techniques":
      - advanced-monitoring/automating-configuration.md
      - advanced-monitoring/vmware-monitoring.md
      - advanced-monitoring/website-monitoring.md
  - "Discovery":
      - discovery/network-discovery.md
      - discovery/active-agent-registration.md
      - discovery/low-level-discovery.md
  - "Specialized Monitoring":
      - specialized-monitoring/SNMP-monitoring.md
      - specialized-monitoring/SNMP-traps-monitoring.md
      - specialized-monitoring/JAVA-monitoring.md
      - specialized-monitoring/IPMI-monitoring.md
  - "Authentication and Security":
      - authentication/HTTP-authentication.md
      - authentication/LDAP-authentication.md
      - authentication/SAML-authentication.md
      - authentication/MFA-support.md
  - "Working with Proxies":
      - proxies/installing-proxies.md
      - proxies/active-proxies.md
      - proxies/passive-proxies.md
      - proxies/loadbalancing-proxies.md
  - "Security Best Practices":
      - security/securing-the-frontend.md
      - security/using-selinux.md
  - "Maintenance and Monitoring Windows":
      - maintenance-windows/windows-monitoring.md
      - maintenance-windows/maintaining-zabbix.md
  - "Zabbix API":
      - api/using-zabbix-api.md

theme:
  language: en
  name: material
  custom_dir: docs/overrides
  font:
    text: Roboto
    code: Nunito
  icon:
    logo: material/library
  features:
    - header.autohide
    - navigation.sections
    #     - navigation.instant can't be used with i18n
    - navigation.expand
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

# Plugins
plugins:
  - search
  - i18n:
      reconfigure_material: true
      fallback_to_default: true
      docs_structure: suffix
      languages:
        - locale: fr
          name: Français
          build: true
        - locale: de
          name: German
          build: true
        - locale: it
          name: Italian
          build: true
        - locale: nl
          name: Nederlands
          build: true
        - locale: pt
          name: Portuguese
          build: true
        - locale: es
          name: Spanish
          build: true
        - locale: th
          name: ภาษาไทย
          build: true
        - locale: zh
          name: 中国人
          build: true
        - locale: en
          default: true
          name: English
          build: true

  - print-site:
      add_to_navigation: false
      print_page_title: "Print Book"
      # Table of contents
      add_table_of_contents: true
      toc_title: "Table of Contents"
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.progressbar
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
