name: ci
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install idna mkdocs-material mkdocs-static-i18n mkdocs-print-site-plugin mkdocs-spellcheck[all] mkdocs-autolinks-plugin mkdocs-mermaid2-plugin
      - run: mkdocs gh-deploy --force
